# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

variables:
  buildConfiguration: 'Release'

pool:
  vmImage: 'ubuntu-latest'

steps: 
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/*Inquiry/*Inquiry.Function/*.csproj'
    arguments: '--output $(Build.BinariesDirectory)/publish_output  --configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: '**/*Inquiry.Func.UnitTests/*UnitTests.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'
    
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.BinariesDirectory)/publish_output'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    
    